### ISSUE TITLE
Thanks for tmux config

### ISSUE THREAD

**Issue by knuckolls** [danemacmillan/dotfiles#13]
I couldn't think of how to tell you this other than a github issue but your tmux config is the best "out of the box" tmux experience i've ever had. Everything just works and is nice on iTerm2 & Mojave, especially the mouse.

https://github.com/danemacmillan/dotfiles/blob/30beada3b9366a305a81c2960b99528858b064f7/home/.config/tmux/tmux.conf

Nothing but a thanks. Have a great day. :wave:

**Comment by danemacmillan** [comment]
Hey! Super happy to hear this. 🎉 

I have to ask: how did you find it?

**Comment by knuckolls** [comment]
You know, you just google stuff to death when it's in your way sometimes. How I made my way to your gem is lost to the sands of time. :)

**Comment by danemacmillan** [comment]
Definitely. 

Just an FYI, tmux released version 2.9, which introduced backwards-incompatible changes to styling, which throw numerous errors upon opening tmux. I've made the modifications if you want to port them into your config: https://github.com/danemacmillan/dotfiles/commit/23f4dba41d313e1d04f70e9495a566fed0baa709

**Comment by knuckolls** [comment]
Just pulled this in on the new Clear Linux dual boot I'm trying out. Works like a charm and is still the best. Thanks :)
