### ISSUE TITLE
Alacritty crashes when trying to start it maximized

### ISSUE THREAD

**Issue by silpheel** [danemacmillan/dotfiles#18]
https://github.com/danemacmillan/dotfiles/blob/667d207f081425efd33a9c2a279b9ece815b2727/home/.config/alacritty/alacritty.yml#L63

This line causes Alacritty 0.4.0 to crash when using Catalina (reported [here](https://github.com/jwilm/alacritty/issues/2877) for Alacritty). Any other listed value for statup_mode will work and the window can be maximized later. The linked issue was closed recently but a fixed version is not yet available on brew.

**Comment by danemacmillan** [comment]
Ah ha--so that was the issue. It looks like it was released the day after this ticket: https://github.com/alacritty/alacritty/releases/tag/v0.4.1
