### ISSUE TITLE
Update to support M-series processors

### ISSUE THREAD

**Issue by silpheel** [danemacmillan/dotfiles#23]
While trying to install the dotfiles on a M1 Mac, there were a few things I had to tinker with. It's a fresh Monterey install on M1 Mac, 2022-10-13:
## brew
- there's a warning about the ruby installer being deprecated, with a suggested command `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"` to replace it. As I got the below error that stopped me, I figured I may as well update this.
- on M1, the brew install directory changes from `/usr/local` to `/opt/homebrew` (see also https://github.com/Homebrew/brew/issues/9177 and https://apple.stackexchange.com/questions/437618/why-is-homebrew-installed-in-opt-homebrew-on-apple-silicon-macs)

My own commit was a quick-and-dirty test to make it work on the M1 Mac but the better solution would account for the hardware properly and still work for Intel, so I did not make a PR and instead just use it as reference: https://github.com/silpheel/dotfiles/commit/9d21f5bfcad93e1af384e89d83f4b4c563713e7d
To detect M-series or Intel it should be enough to check if `uname -m` returns `arm64` or `x86_64` respectively.

## Rosetta
We can install Rosetta automatically, which will be handy because something at this stage surely will need it.
`sudo softwareupdate --install-rosetta --agree-to-license`
As above, this should only be done on `arm64`

## stow
It seems that stow is used as part of the install process but before brew has a chance to install packages. This would work as an update, but not an an initial install.
For my needs, I had brew installed by the time it failed, so I installed the package and restarted the installation process.

**Comment by danemacmillan** [comment]
See #24 and #25 for details. This is complete.
